
export const STORE_PROFILE = 'STORE_PROFILE';
export const STORE_TOKEN_ACCESS = 'STORE_TOKEN_ACCESS';
export const STORE_DATA_TOKEN = 'STORE_DATA_TOKEN';

export const STORE_BOX_OPERATION_FLOW = 'STORE_BOX_OPERATION_FLOW';

